### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [32, 3, 1, 1], expected input[128, 36, 207, 1] to have 3 channels, but got 1 channels instead

### ISSUE THREAD

**Issue by Leihang999** [zhengdaoli/AGC-net#3]
不知道为什么一直报这个通道错误，，feature_len是按你设置的3，但是报错一直说实际数据是1
Traceback (most recent call last):
  File "main.py", line 200, in <module>
    rnn_train(args, datasets, scaler)
  File "main.py", line 92, in rnn_train
    loss, mae, mape, rmse = trainer.train(input_data, target)
  File "/root/AGC-net-main/model.py", line 742, in train
    output, h = self.model(input_data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/AGC-net-main/model.py", line 122, in forward
    out, _ = self.forward_one(h_x)
  File "/root/AGC-net-main/model.py", line 149, in forward_one
    residual = F.relu(self.upsampling(x))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 3, 1, 1], expected input[128, 36, 207, 1] to have 3 channels, but got 1 channels instead

**Comment by Leihang999** [comment]
Traceback (most recent call last):
  File "main.py", line 200, in <module>
    rnn_train(args, datasets, scaler)
  File "main.py", line 92, in rnn_train
    loss, mae, mape, rmse = trainer.train(input_data, target)
  File "/root/AGC-net-main/model.py", line 743, in train
    output, h = self.model(input_data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/AGC-net-main/model.py", line 122, in forward
    out, _ = self.forward_one(h_x)
  File "/root/AGC-net-main/model.py", line 150, in forward_one
    residual = F.relu(self.upsampling(x))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 3, 1, 1], expected input[128, 1, 207, 12] to have 3 channels, but got 1 channels instead

**Comment by Leihang999** [comment]
什么都没动，就把数据集弄好了，然后按你的运行

**Comment by 33yeah123** [comment]
> 不知道为什么一直报这个通道错误，，feature_len是按你设置的3，但是报错一直说实际数据是1 Traceback (most recent call last): File "main.py", line 200, in rnn_train(args, datasets, scaler) File "main.py", line 92, in rnn_train loss, mae, mape, rmse = trainer.train(input_data, target) File "/root/AGC-net-main/model.py", line 742, in train output, h = self.model(input_data) File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/root/AGC-net-main/model.py", line 122, in forward out, _ = self.forward_one(h_x) File "/root/AGC-net-main/model.py", line 149, in forward_one residual = F.relu(self.upsampling(x)) File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward return self._conv_forward(input, self.weight, self.bias) File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: Given groups=1, weight of size [32, 3, 1, 1], expected input[128, 36, 207, 1] to have 3 channels, but got 1 channels instead

你好，想问下那个.h5文件怎么来的

**Comment by wdlovecjy** [comment]
你好，我也遇到了这个问题
可以帮忙解决下吗，谢谢您了

**Comment by Leihang999** [comment]
没有弄了，这个模型结构太简单，不太好魔改




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhengdaoli/AGC-net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月11日(星期二) 晚上10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhengdaoli/AGC-net] RuntimeError: Given groups=1, weight of size [32, 3, 1, 1], expected input[128, 36, 207, 1] to have 3 channels, but got 1 channels instead (Issue #3)





 
你好，我也遇到了这个问题
 可以帮忙解决下吗，谢谢您了
